export const HOMEPAGE = "/";
export const SIGNUPPAGE = "/auth/signup";
export const LOGINPAGE = "/auth/login";
export const PROTECTEDPAGE = "/protected";
export const USERPROFILE = "/profile";
// export const AUTH = "/auth/loginn";
export const SHOP = "/shop";
export const PRODUCTDETAIL = "/products/:id";
export const CART = "/cart";
